# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
- task: TerraformTaskV3@3
  inputs:
    provider: 'gcp'
    command: 'init'
    backendServiceGCP: 'gcp-sc'
    backendGCPBucketName: 'rohit-46'
- task: TerraformTaskV3@3
  inputs:
    provider: 'gcp'
    command: 'plan'
    environmentServiceNameGCP: 'gcp-sc'
- task: TerraformTaskV3@3
  inputs:
    provider: 'gcp'
    command: 'apply'
    commandOptions: '--auto-approve'
    environmentServiceNameGCP: 'gcp-sc'